import fs from 'node:fs'
import path from 'node:path'
import { test, expect } from './fixtures.js'
import { visitAndApproveStorage } from './helpers.js'

// Load -> save -> load must stop changing after one pass, for drawings that use
// the features that persist state in the document: frames, corner radius, taper,
// shadow/outline filters, text-on-path, groups with transforms, extra layers,
// repeat/mirror stamps and puppet-warp rigs.
//
// The fixtures in tests/e2e/fixtures/roundtrip/ were generated by driving the
// real tools in a browser and are committed as-is, so they also stand in for
// "drawings saved by an earlier version": a change to the serializer/loader
// that would corrupt or keep rewriting existing drawings fails here.
// (corner-radius.svg and taper.svg were saved before the `xmlns:se` fix, so
// they also cover the load-time repair of an undeclared `se:` prefix.)
const dir = path.join(process.cwd(), 'tests/e2e/fixtures/roundtrip')
const fixtures = fs.readdirSync(dir).filter(f => f.endsWith('.svg')).sort()

test.describe('document round trip', () => {
  test.beforeEach(async ({ page }) => {
    await visitAndApproveStorage(page)
  })

  for (const file of fixtures) {
    test(`${file} loads, then stabilises after one save/load pass`, async ({ page }) => {
      const svg = fs.readFileSync(path.join(dir, file), 'utf8')

      const passes = await page.evaluate((src) => {
        const c = window.svgEditor.svgCanvas
        const shape = (xml) => {
          const doc = new DOMParser().parseFromString(xml, 'image/svg+xml')
          const counts = {}
          for (const el of doc.querySelectorAll('*')) {
            counts[el.localName] = (counts[el.localName] || 0) + 1
            for (const a of el.attributes) {
              if (a.name.startsWith('se:') || a.name.startsWith('data-')) {
                counts[`@${a.name}`] = (counts[`@${a.name}`] || 0) + 1
              }
            }
          }
          return { counts, wellFormed: !doc.querySelector('parsererror') }
        }
        const out = []
        let cur = src
        for (let i = 0; i < 4; i++) {
          const ok = c.setSvgString(cur)
          cur = c.getSvgString()
          out.push({ ok, svg: cur, ...shape(cur) })
        }
        return out
      }, svg)

      for (const [i, p] of passes.entries()) {
        expect(p.ok, `pass ${i}: setSvgString`).toBe(true)
        expect(p.wellFormed, `pass ${i}: saved output is well-formed XML`).toBe(true)
      }
      // Stable after the first save/load: further passes must not change anything.
      expect(passes[2].svg).toBe(passes[1].svg)
      expect(passes[3].svg).toBe(passes[2].svg)
      // And nothing structural (elements, se:/data- attributes) is lost on the first pass.
      expect(passes[1].counts).toEqual(passes[0].counts)
    })
  }
})
